/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'reid.dev' at '10/3/15 6:29 PM' with Gradle 2.3
 *
 * @author reid.dev, @date 10/3/15 6:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
